Starting page
HubertLegec/CodersCamp2020-Chess pull request #8
Opened 2021-01-24 16:07 UTC by EsDawid

2021-01-25 20:41 UTC, HubertLegec requested changes

2021-01-25 20:41 UTC, HubertLegec commented on src/app/startingPanelManager.ts
> +export class startingPanelManager {
Nazwy klas powinny zaczynać się dużą literą

2021-01-25 20:41 UTC, HubertLegec commented on src/app/startingPanelManager.ts
> +        let logo: HTMLElement = document.createElement('h3');
używajcie `const` wszędzie gdzie zmienna cały czas wskazuje na ten sam obiekt. Zasada jest taka, że z defaultu używamy `const` a `let` tylko tam gdzie potrzebujemy przypisywać różne wartości do tej samej zmiennej.

2021-01-25 20:41 UTC, HubertLegec commented on src/app/startingPanelManager.ts
> +        startGameButton.addEventListener('click', (): void => {
czy podawanie tutaj tego `void` jest do czegoś potrzebne? To generalnie zaciemnia kod, jeśli podajemy typy w lambdach. TS sobie sam rozkmini jaki jest typ.

2021-01-25 20:41 UTC, HubertLegec commented on test/startingPanelManager.test.ts
> +        const nameSettings = document.getElementById('nameSettings');
Tutaj nie sprawdzałbym czy jest tworzony `nameSettings` czy jakikolwiek inny div. Ogólnie ten test jest zbędny moim zdaniem. Ważne jest że wyświetlone będą inputy gdzie można wpisać imiona graczy i to jest sprawdzone w następnym teście. Tak samo że jest lider i na to też jest dalej test. Strukura divów niewidocznych dla użytkownika nie ma znaczenia w testach.

2021-01-25 20:41 UTC, HubertLegec commented on test/startingPanelManager.test.ts
> +        expect(sliderValue.textContent).toEqual(slider.value);
Tutaj bym sprawdził metodą `getByText` że 30 jest widoczne na ekranie zamiast wyciągania po ID elementu

2021-01-26 07:20 UTC, EsDawid commented on src/app/startingPanelManager.ts
> +        startGameButton.addEventListener('click', (): void => {
mowa o void w lambdach czy ogólnie przy funkcjach?

2021-01-26 15:59 UTC, HubertLegec approved these changes

2021-01-26 16:06 UTC, merged