Board
HubertLegec/CodersCamp2020-Chess pull request #9
Opened 2021-01-26 20:53 UTC by EsDawid

2021-01-27 19:12 UTC, HubertLegec requested changes

2021-01-27 19:12 UTC, HubertLegec commented on test/startingPanelManager.test.ts
> +        [
Nie rozumiem po co ta tablica. Jeśli chcesz przetestować scenariusze, że wpisujesz tylko jedno imię i button jest wciąż zablokowany, to powinien być to oddzielny test parametryzowany.
Ten test powinien sprawdzać wyłącznie przypadek gdzie wpisujemy obie wartości i button nie jest zablokowany.

2021-01-27 19:12 UTC, HubertLegec commented on test/boardDisplay.test.ts
> +        opponentFiles.forEach((v: HTMLElement, i: number) => {
to jest mega skomplikowane sprawdzanie, robił bym to raczej tak:
```
expect(opponentFiles.map(f => f.textContent)).isEqualTo(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'])
```

2021-01-28 06:48 UTC, EsDawid commented on src/app/App.ts
> +
Coś importowałem i pewnie przez przypadek została ta pusta linia

2021-01-28 06:51 UTC, EsDawid commented on src/app/boardDisplay.ts
> +    createChessBoard(): void {
Na razie może bym to zostawił przed demo, a można to przegadać dzisiaj

2021-01-28 07:00 UTC, EsDawid commented on src/app/startingPanelManager.ts
> +            document.getElementById('gameStartButton').removeAttribute('disabled')
Wczoraj rano zrobiłem pusha z tą funkcjonalnością, bo też się ogarnąłem, że po usunięciu będzie nadal odblokowany.  Nawet na branchu jest linia odpowiedzialna za to:

        else document.getElementById('gameStartButton').setAttribute('disabled', 'true')
    }
    
    oraz odpowiednie wywoływanie w funkcji monitorującej:
    
            else {
                this.flagInputOne = false;
                this.watchInputFlags();
            }

2021-01-28 16:01 UTC, mbr95 approved these changes

2021-01-28 19:11 UTC, HubertLegec requested changes

2021-01-28 19:11 UTC, HubertLegec commented on src/app/landingPage.ts
> +    private board = new BoardView('chess-app');
landing page nie powinien nic wiedzieć o boardzie, to są zupełnie dwa oddzielne ekrany. Instancja klasy `BoardView` powinna powstać w `App`

2021-01-28 19:11 UTC, HubertLegec commented on src/app/App.ts
> +  let startingPanel = new LandingPage('chess-app')
można już zmienić nazwę zmiennej żeby odpowiadała klasie

2021-01-28 19:11 UTC, HubertLegec commented on src/app/landingPage.ts
> +    createStartingPage() {
może po prostu `create`? StartingPage nie pasuje do nazwy klasy

2021-02-04 21:19 UTC, HubertLegec commented on src/app/LandingPage.ts
> +    private setButtonHref() {
Trochę to pokręcone że w każdym event listenerze jest aktualizacja href. Nie lepiej byłoby programowo obsłużyć `onClick` na buttonie i zrobić `window.open` ?

2021-02-04 21:19 UTC, HubertLegec commented on src/app/URLParameters.ts
> +    getParams() {
a dlaczego nie oddzielny getter na pobranie każdego gracza i czasu? Wrzucenie parametrów do tablicy pogarsza czytelność

2021-02-04 21:19 UTC, HubertLegec commented on test/URLParameters.test.ts
> +        expect(params[0]).toEqual('green');
zamiast zwracania tablicy proponuję geter dla `player1`, `player2`

2021-02-04 21:19 UTC, HubertLegec commented on test/landingPage.test.ts
> +        <h3 id="codersLogo">.CodersCrew</h3>
może zamiast pisania całego HTMLa ręcznie to dałoby się go zaczytać z pliku? coś takiego jak tutaj:
https://dev.to/snowleo208/things-i-learned-after-writing-tests-for-js-and-html-page-4lja

2021-02-04 21:19 UTC, HubertLegec commented on test/landingPage.test.ts
> +        expect(buttonLink.href).toContain('chessGame.html?name1=red&name2=blue&time=33');
tutaj lepiej byłoby przetestować, że po kliknięciu w button przechodzimy na inną ścieżkę 

2021-02-05 11:24 UTC, HubertLegec approved these changes

2021-02-05 11:25 UTC, merged